name: Test and Build
on:
  - push
  - pull_request

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.1'
      - name: Tests
        run: |
          make fmt
          make vet
          make test
          make build
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.27
      - name: Build release type artifacts
        run: make release
